### ISSUE TITLE
Test: Create test for EventsPage api

### ISSUE THREAD

**Issue by dricazenck** [Women-Coding-Community/wcc-backend#82]
Build the tests for the /events api

**Comment by goelsonali** [comment]
These tests were added and passed
<img width="992" alt="Screenshot 2024-09-14 at 13 44 59" src="https://github.com/user-attachments/assets/3ce34b5a-9697-4163-a76c-ffc5c7761d5f">
<img width="1228" alt="Screenshot 2024-09-14 at 13 45 14" src="https://github.com/user-attachments/assets/0254f4d0-6518-430c-8de9-34ac339bb9e1">
